# Étape 1 : Image Maven avec JDK 21
FROM maven:3.9-eclipse-temurin-21 AS dev

WORKDIR /app

COPY pom.xml .
RUN mvn dependency:go-offline

# Monter le code source en volume (via docker-compose)
COPY src ./src

# Activer le hot reload avec DevTools + Debug
CMD ["mvn", "spring-boot:run"]
